//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maximus.ControlCenter.UI.Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maximus.ControlCenter.UI.Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList&gt;
        ///  &lt;Query Id=&quot;0&quot; Path=&quot;Application&quot;&gt;
        ///    &lt;Select Path=&quot;Application&quot;&gt;*[System[(Level=1  or Level=2 or Level=3)]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Security&quot;&gt;*[System[(Level=1  or Level=2 or Level=3)]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[(Level=1  or Level=2 or Level=3)]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;HardwareEvents&quot;&gt;*[System[(Level=1  or Level=2 or Level=3)]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;HP Analytics&quot;&gt;*[System[(Level=1  or Level=2 or Level=3)]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;IntelAudioServiceLog&quot;&gt;* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventXPath_Administrative_Events {
            get {
                return ResourceManager.GetString("EventXPath_Administrative Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList&gt;
        ///  &lt;Query Id=&quot;0&quot; Path=&quot;Microsoft-Rdms-UI/Admin&quot;&gt;
        ///    &lt;Select Path=&quot;Microsoft-Rdms-UI/Admin&quot;&gt;*&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Microsoft-Rdms-UI/Operational&quot;&gt;*&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Remote-Desktop-Management-Service/Admin&quot;&gt;*&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Remote-Desktop-Management-Service/Operational&quot;&gt;*&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Microsoft-Windows-TerminalServices-SessionBroker-Client/Admin&quot;&gt;*&lt;/Select&gt;
        ///    &lt;Select Path=&quot;Microsoft-Windows-TerminalServices-SessionBroker-Client/Operational&quot;&gt;*&lt;/Sel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventXPath_Remote_Desktop_Services {
            get {
                return ResourceManager.GetString("EventXPath_Remote Desktop Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList&gt;
        ///  &lt;Query Id=&quot;0&quot; Path=&quot;System&quot;&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[Provider[@Name=&apos;Microsoft-Windows-IIS-APPHOSTSVC&apos;]]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[Provider[@Name=&apos;Microsoft-Windows-IIS-FTP&apos;]]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[Provider[@Name=&apos;Microsoft-Windows-IIS-IisMetabaseAudit&apos;]]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[Provider[@Name=&apos;Microsoft-Windows-IIS-IISReset&apos;]]]&lt;/Select&gt;
        ///    &lt;Select Path=&quot;System&quot;&gt;*[System[Provider[@Name=&apos;Microsoft-Windows-IIS-W3SVC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventXPath_Web_Server {
            get {
                return ResourceManager.GetString("EventXPath_Web Server", resourceCulture);
            }
        }
    }
}
